version: '3'

services:
  db:
    image: postgres:latest
    container_name: tasks-manager-db
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: tasks-manager
    ports:
      - "5432:5432"
